replace innerHTML with TT friendly ways
This will enable usage in [Trusted Types](https://developer.mozilla.org/en-US/docs/Web/API/Trusted_Types_API)
context.
As Element.innerHTML is considered to be dangerous injection sink, its usage is denied
when `Content-Security-Policy` enforces `require-trusted-types-for 'script'` directive.

E.g. it throws something like this from `clearElement` function:
```
TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at D.clearElement (xyz.js:733:62)
    at D.start (xyz.js:710:176)
```

[textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innerhtml) in MDN.
[replaceChildren](https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren) has [~91% coverage](https://caniuse.com/mdn-api_element_replacechildren)